name: Staging Loader Functions Deployment

on:
  push:
    branches:
      - main
    paths:
      - "loaders/**"
      - ".github/workflows/deploy_loaders_stag.yaml"

env:
  FUNCTION_APP_NAME: bb-loaders-stag2
  RESOURCE_GROUP_NAME: alexBootcampBenchmarkStaging
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./loaders"
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_2 }}

defaults:
  run:
    working-directory: loaders

jobs:
  TestAndLint:
    runs-on: ubuntu-latest
    name: Test and Lint

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password123
          POSTGRES_USER: db_admin
          POSTGRES_HOST_AUTH_METHOD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python with pip dependency cache
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"

      - name: install dependencies
        shell: bash
        run: pip install -r requirements.txt

      - name: lint
        run: make lint

      - name: test
        run: make unit_test
        env:
          PSQL_CONNECTIONSTRING: "host='localhost' user='db_admin' password='password123' dbname='test_db'"

      - name: function conformity
        run: make func_check

  StagingLoaderFunctionsDeployment:
    runs-on: ubuntu-latest
    needs: TestAndLint
    name: Staging Functions Deployment

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python with pip dependency cache
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"

      - name: install python dependencies
        shell: bash
        run: |
          pushd './.'
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: get function app publish profile
        id: profilevar
        run: |
          publish_profile=$(az functionapp deployment list-publishing-profiles --name ${{ env.FUNCTION_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}  --xml)
          echo "publish_profile=$publish_profile" >> $GITHUB_OUTPUT

      - name: run azure functions action
        uses: Azure/functions-action@v1.3.2
        with:
          app-name: ${{ env.FUNCTION_APP_NAME}}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ steps.profilevar.outputs.publish_profile }}
          scm-do-build-during-deployment: true
          enable-oryx-build: false
