name: Function Deployment

on:
  push:
    branches: main

env:
  FUNCTION_APP_NAME: helloworld12321

jobs:
  FunctionDeployment:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: install python dependencies
        shell: bash
        run: |
          pushd './.'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: get function app publish profile
        id: profilevar
        run: |
          publish_profile=$(az functionapp deployment list-publishing-profiles --name ${{ env.FUNCTION_APP_NAME }} --resource-group bootcampBenchmarkResourceGroup --xml)
          echo "publish_profile=$publish_profile" >> $GITHUB_OUTPUT

      - name: run azure functions action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME}}
          publish-profile: ${{ steps.profilevar.outputs.publish_profile }}
          # scm-do-build-during-deployment: true
          enable-oryx-build: false
