name: Function Deployment

on:
  push:
    branches: main

jobs:
  FunctionDeployment:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: install python dependencies
        shell: bash
        run: |
          pushd './.'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Deploy Azure Functions
        uses: Azure/cli-action@v1
        with:
          azcliversion: "latest"
          inlineScript: |
            az functionapp deployment source config-zip -g bootcampBenchmarkResourceGroup -n helloworld12321 .

      # - name: "Run Azure Functions action"
      #   uses: Azure/functions-action@v1
      #   with:
      #     app-name: helloworld12321
      #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      #     scm-do-build-during-deployment: true
      #     enable-oryx-build: true
