name: Function Deployment

on:
  push:
    branches: main

jobs:
  FunctionDeployment:
    runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: "Run Azure Functions action"
      uses: Azure/functions-action@v1
      with:
        app-name: helloworld12321
        package: "."
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
