name: Function Deployment

on:
  push:
    branches: add_publish_profile_to_secrets

jobs:
  FunctionDeployment:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: install python dependencies
        shell: bash
        run: |
          pushd './.'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test publish profile retrieval
        id: profilevar
        run: |
          publish_profile=$(az functionapp deployment list-publishing-profiles --name helloworld12321   --resource-group bootcampBenchmarkResourceGroup --xml)
          echo "publish_profile=$publish_profile" >> $GITHUB_OUTPUT

      - name: "Run Azure Functions action"
        uses: Azure/functions-action@v1
        with:
          app-name: helloworld12321
          publish-profile: ${{steps.profilevar.outputs.publish_profile}}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
